### ISSUE TITLE
Playback stops after 60 seconds

### ISSUE THREAD

**Issue by itniels** [jack3898/discord-yt-bot#22]
Seems the bot only plays for 60 seconds, I have seen other bots do this as well in my testing today, so probably not specific to this, not sure if they have made an update to how bots can transmit audio or something along those lines.

**Comment by jack3898** [comment]
> Seems the bot only plays for 60 seconds, I have seen other bots do this as well in my testing today, so probably not specific to this, not sure if they have made an update to how bots can transmit audio or something along those lines.

Yes I am currently working on the queue in a separate branch with a fix (I hope, seems to work fine) so hopefully soon it'll work! Might commit to master to get it up to date asap. 🙂

**Comment by itniels** [comment]
That would be awesome 🙂 
Let me know and I can test it quickly on my server.

**Comment by itniels** [comment]
@jack3898 I gave it a shot, but no change, still stops playing after ~60 seconds.
![image](https://user-images.githubusercontent.com/15611687/228205820-0863449f-e787-4619-a40b-dcd5118d571f.png)

**Comment by jack3898** [comment]
Ugh darn 😔

Maybe a rollback to an earlier version of discord.js/voice will do the trick. Or an update. But I'll have a look, it is a very common issue by the looks of things.

**Comment by jack3898** [comment]
I believe I have fixed it in my branch. It has required a lot of changes that are not easy to implement in master (due some big refactors I have done in the other branch). But rest assured, I have recreated the issue and it is working great now!

**Comment by itniels** [comment]
That's great @jack3898 thank you very much, I appreciate you work and time very much 😊
When you have a version or branch I can try let me know 🚀

**Comment by jack3898** [comment]
You can `git fetch` then `git checkout 20-make-play-command-consume-a-queue` to try the fix

- Do `yarn install` for latest deps
- Delete the `app.db` in `packages\database\app.db`
- Run `yarn run db:push` then `yarn run db:seed`
- `yarn run dev` to start the bot in dev mode

Let me know if it works on your end! Hopefully I didn't miss any steps. 🤣

**Comment by jack3898** [comment]
The `/play` command has changed as well, it requires a couple more arguments. You will want to set the first option to `search` then provide a url as the resource.

![image](https://user-images.githubusercontent.com/28375223/228364822-ef3ba318-0708-418a-b630-2b08153ad85a.png)

Do keep in mind there is a bug where the track will loop when it finishes when playing a single track! I am working on that. 👍

**Comment by itniels** [comment]
@jack3898 Awesome :)
I will not have time to test right now, but will give it a spin tomorrow and report back!
Thank you so much 😊

**Comment by jack3898** [comment]
Brill! Just fixed that looping bug too but just keep in mind the branch is not finished yet! 😄

**Comment by itniels** [comment]
Good morning @jack3898 🙂 Not working unfortunately, it never joins the voice channel now.
It does print out: "Now playing the audio" but nothing happens, I have attached the logs from console
![image](https://user-images.githubusercontent.com/15611687/228426169-92a9fd51-0139-49cf-85fd-223286d0e2b5.png)

**Comment by itniels** [comment]
Good morning @jack3898 🙂 Not working unfortunately, it never joins the voice channel now.
It does print out: "Now playing the audio" but nothing happens, I have attached the logs from console

![image](https://user-images.githubusercontent.com/15611687/228426475-8649a352-3a48-4f9a-bd91-cad83c28a280.png)

**Comment by jack3898** [comment]
Usually that means the resource is not valid (I have booked the error message from main in that branch 😂).

Is the URL or video id right, is it a public video, not age restricted, made for kids etc? I haven't tried it with the shortened URL yet but it seemed to work with the long URL and or video id.

**Comment by itniels** [comment]
Video is valid, and tried it before switching branch where it worked fine.
ID: `https://www.youtube.com/watch?v=1mWa28odcds`

Hmm not sure, it does have the "type"?

![image](https://user-images.githubusercontent.com/15611687/228451241-1ba3fba6-975a-461a-89c7-8ef88730b657.png)

**Comment by itniels** [comment]
Ohh wait!! it was missing the ressource!, if i tab adn get it to show, then it works! 😅 

Like this:
![image](https://user-images.githubusercontent.com/15611687/228451863-bb7f61ac-8f6e-4c8f-9dc4-224b05aed1ca.png)

**Comment by jack3898** [comment]
Ahhhh, maybe the ux there is not optimal. Might shift the queue stuff to a different command maybe 🤔 but glad it's working now 🤣

I hope to merge the changes into main soon, there are some finishing touches I need to apply and then some unit tests and it'll be ready.

**Comment by itniels** [comment]
Awesome work @jack3898 😊 really appreciate it!
If the global commands are not working optimal, the usual `!play <url>` that many bots have would work fine too, but I do see the /play an do some cool stuff :)

**Comment by jack3898** [comment]
Yeah in the future play will work with search terms, queues and more. Tricky thing is, slash commands are flexible, but not flexible enough (I picture the /play command getting complicated)! I'll see what I can do. 🤔

**Comment by jack3898** [comment]
I've merged the new queue stuff into master. Haven't been able to get the bot to disconnect mid-voice now! I'll close this issue as I believe it is fixed. 👍

**Comment by jack3898** [comment]
It's also worth noting /play is only used for queues now. If you want to play something without queues use /quickplay. :)

**Comment by itniels** [comment]
Thank you so much! :) 
I apologize for the slow response, I will give it a try here in a little bit

**Comment by itniels** [comment]
@jack3898 I just updated to latest `main` and it is working flawlessly 💖
the `/quickplay` is a really nice addition! 😎 

Thank you so much for all your hard work on this!
